### ISSUE TITLE
Won't build on Windows

### ISSUE THREAD

**Issue by oliversalzburg** [Ajido/node-identicon#8]
Here's the log for the build process:

```shell
$ npm install --save identicon
\
> canvas@1.1.6 install d:\project\node_modules\identicon\node_modules\canvas
> node-gyp rebuild


d:\project\node_modules\identicon\node_modules\canvas>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  PixelArray.cc
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\Canvas.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\CanvasGradient.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\canvas.vcxp
roj]
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\init.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\CanvasRenderingContext2d.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\c
anvas.vcxproj]
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\Image.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\ImageData.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\CanvasPattern.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\canvas.vcxpr
oj]
d:\project\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\PixelArray.cc) [d:\project\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\project\node_modules\identicon\node_modules\canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "identicon"
npm ERR! cwd d:\project
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by colkito** [comment]
Have you tried the new version? @oliversalzburg

**Comment by oliversalzburg** [comment]
Still failing, this is the current output:

```

> canvas@1.2.3 install f:\temp\node_modules\identicon\node_modules\canvas
> node-gyp rebuild


f:\temp\node_modules\identicon\node_modules\canvas>if not defined npm_config_node_gyp (node "c:\Users\Oliver\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild) 
Using overrides found in C:\Users\Oliver\.gyp\include.gypi
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\CanvasGradient.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\CanvasGradient.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\CanvasPattern.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
  PixelArray.cc
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\Image.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\ImageData.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\Canvas.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\init.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\CanvasPattern.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\Image.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\ImageData.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\Canvas.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\CanvasRenderingContext2d.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\init.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\CanvasRenderingContext2d.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5205): warning C4512: 'v8::ExtensionConfiguration' : assignment operator could not be generated (..\src\PixelArray.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\Oliver\.node-gyp\0.12.3\deps\v8\include\v8.h(5193) : see declaration of 'v8::ExtensionConfiguration'
f:\temp\node_modules\identicon\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo/cairo.h': No such file or directory (..\src\PixelArray.cc) [f:\temp\node_modules\identicon\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Users\Oliver\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Users\\Oliver\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd f:\temp\node_modules\identicon\node_modules\canvas
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Oliver\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "identicon"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     f:\temp\npm-debug.log
```

I guess I need the cairo sources for canvas to be built correctly. I'm not quite sure how to do that, yet ;D

**Comment by oliversalzburg** [comment]
After reading the [Windows Installation guide for node-canvas](https://github.com/Automattic/node-canvas/wiki/Installation---Windows), I realized that I need to install GTK2.

After installing GTK2, as described in the article above, node-identicon installs fine :+1: :)
